# API Version for core Secret resource
apiVersion: v1

# Kind specifies Secret parameter store
kind: Secret

# Metadata configuration template
metadata:
  name: {{ include "todo-app.fullname" . }}-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}

type: Opaque

# Sensitive values dynamically rendered from values.yaml
data:
  API_SECRET_KEY: {{ .Values.secrets.API_SECRET_KEY | quote }}
